"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard_weather from './dashboard-weather.bones.json'
import _dashboard_free_time from './dashboard-free-time.bones.json'
import _dashboard_schedule from './dashboard-schedule.bones.json'
import _dashboard_today_classes from './dashboard-today-classes.bones.json'
import _schedule_page_list from './schedule-page-list.bones.json'
import _settings_page from './settings-page.bones.json'
import _profile_page from './profile-page.bones.json'
import _reminders_tab_list from './reminders-tab-list.bones.json'
import _admin_page from './admin-page.bones.json'
import _notifications_tab_list from './notifications-tab-list.bones.json'

configureBoneyard({"color":"#e7e5e4","darkColor":"#292524","animate":"shimmer","shimmerColor":"#f5f5f4","darkShimmerColor":"#44403c","speed":"1.3s","shimmerAngle":110})

registerBones({
  "dashboard-weather": _dashboard_weather,
  "dashboard-free-time": _dashboard_free_time,
  "dashboard-schedule": _dashboard_schedule,
  "dashboard-today-classes": _dashboard_today_classes,
  "schedule-page-list": _schedule_page_list,
  "settings-page": _settings_page,
  "profile-page": _profile_page,
  "reminders-tab-list": _reminders_tab_list,
  "admin-page": _admin_page,
  "notifications-tab-list": _notifications_tab_list,
})
